#!/usr/bin/env python3
"""
FPGA-Litho BRAM Version C Simulation Runner
运行BRAM版本的C仿真验证

目标:
- 7个测试用例全部通过
- 验证BRAM存储功能
- 验证AXI-Lite接口
- 验证参数检查逻辑

使用:
  python run_csynth_bram.py [--verbose]

@author FPGA-Litho Team
@date 2026-04-03
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path

# 项目路径
PROJECT_ROOT = Path(__file__).parent.parent
SCRIPT_DIR = PROJECT_ROOT / "script"
SRC_DIR = PROJECT_ROOT / "src"
TB_DIR = PROJECT_ROOT / "testbench"
INCLUDE_DIR = PROJECT_ROOT / "include"
HLS_PROJ_DIR = PROJECT_ROOT / "hls_litho_system_bram_proj"

def run_command(cmd, cwd=None, verbose=False):
    """运行命令并返回结果"""
    if verbose:
        print(f"Running: {' '.join(cmd)}")
    
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=300  # 5分钟超时
        )
        
        if verbose:
            print(result.stdout)
            if result.stderr:
                print("STDERR:", result.stderr)
        
        return result.returncode, result.stdout, result.stderr
    
    except subprocess.TimeoutExpired:
        print("ERROR: Command timed out after 300 seconds")
        return -1, "", "Timeout"
    except Exception as e:
        print(f"ERROR: Failed to run command: {e}")
        return -1, "", str(e)

def check_vitis_hls():
    """检查Vitis HLS是否可用"""
    # 检查环境变量
    if "XILINX_VITIS" not in os.environ and "XILINX_HLS" not in os.environ:
        print("ERROR: Vitis HLS environment not detected")
        print("Please source Vitis settings script:")
        print("  source /opt/Xilinx/Vitis/2024.1/settings64.sh")
        print("or")
        print("  source /opt/Xilinx/Vivado/2024.1/settings64.sh")
        return False
    
    # 检查vitis_hls命令
    try:
        result = subprocess.run(
            ["vitis_hls", "--version"],
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            print(f"Vitis HLS found: {result.stdout.split()[0:3]}")
            return True
        else:
            print("ERROR: vitis_hls command failed")
            return False
    except FileNotFoundError:
        print("ERROR: vitis_hls command not found")
        return False
    except Exception as e:
        print(f"ERROR: Failed to check Vitis HLS: {e}")
        return False

def create_hls_project(verbose=False):
    """创建HLS项目"""
    print("\n" + "="*60)
    print("Creating HLS Project for BRAM Version")
    print("="*60)
    
    # 创建项目目录
    HLS_PROJ_DIR.mkdir(exist_ok=True)
    
    # 创建TCL脚本
    tcl_script = SCRIPT_DIR / "run_csynth_bram.tcl"
    with open(tcl_script, 'w') as f:
        f.write("""# FPGA-Litho BRAM Version C Simulation TCL Script
# Auto-generated by run_csynth_bram.py

# 打开或创建项目
open_project -reset hls_litho_system_bram_proj

# 添加源文件
add_files ../src/hls_litho_system_bram.cpp

# 添加测试文件
add_files -tb ../testbench/litho_system_bram_tb.cpp

# 设置顶层函数
set_top hls_litho_system_bram

# 打开解决方案
open_solution -reset solution1

# 设置目标设备
set_part {xcku3p-ffvb2104-2-e}

# 创建时钟
create_clock -period 5.0 -name default

# C仿真
csim_design -clean -setup

# 关闭项目
close_project

exit
""")
    
    print(f"Created TCL script: {tcl_script}")
    return True

def run_c_simulation(verbose=False):
    """运行C仿真"""
    print("\n" + "="*60)
    print("Running C Simulation")
    print("="*60)
    
    # 切换到项目根目录
    os.chdir(PROJECT_ROOT)
    
    # 使用TCL脚本运行
    tcl_script = "script/run_csynth_bram.tcl"
    cmd = ["vitis_hls", "-f", tcl_script]
    
    returncode, stdout, stderr = run_command(cmd, verbose=verbose)
    
    # 检查结果
    if returncode == 0:
        print("\nC Simulation completed successfully!")
        
        # 查找仿真输出
        csim_log = HLS_PROJ_DIR / "solution1" / "csim" / "report" / "csim.log"
        if csim_log.exists():
            print(f"\nC Simulation Log: {csim_log}")
            with open(csim_log, 'r') as f:
                log_content = f.read()
                if verbose:
                    print(log_content)
                
                # 检查是否所有测试通过
                if "ALL TESTS PASSED" in log_content:
                    print("\n*** ALL TESTS PASSED ***")
                    return True
                else:
                    print("\nWARNING: Some tests may have failed")
                    if not verbose:
                        print("Run with --verbose for detailed output")
                    return False
        else:
            print("WARNING: Could not find csim.log")
            return True
    else:
        print(f"\nERROR: C Simulation failed with return code {returncode}")
        if stderr:
            print(f"Error: {stderr}")
        return False

def check_results(verbose=False):
    """检查仿真结果"""
    print("\n" + "="*60)
    print("Checking Results")
    print("="*60)
    
    # 检查仿真日志
    csim_log = HLS_PROJ_DIR / "solution1" / "csim" / "report" / "csim.log"
    if not csim_log.exists():
        print("WARNING: C simulation log not found")
        return False
    
    with open(csim_log, 'r') as f:
        content = f.read()
        
        # 提取测试结果
        if "Test Summary" in content:
            # 找到测试总结部分
            summary_start = content.find("Test Summary")
            summary_end = content.find("***", summary_start)
            if summary_start != -1:
                print("\nTest Results:")
                print(content[summary_start:summary_end+50])
        
        # 检查通过率
        if "Passed: 7/7" in content:
            print("\n✓ All 7 tests passed")
            return True
        else:
            print("\n✗ Some tests failed")
            return False

def main():
    """主函数"""
    parser = argparse.ArgumentParser(description='Run FPGA-Litho BRAM C Simulation')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Enable verbose output')
    args = parser.parse_args()
    
    print("="*60)
    print("FPGA-Litho BRAM Version C Simulation")
    print("="*60)
    print(f"Project Root: {PROJECT_ROOT}")
    print(f"HLS Project: {HLS_PROJ_DIR}")
    print("="*60)
    
    # 检查Vitis HLS环境
    if not check_vitis_hls():
        print("\nERROR: Vitis HLS environment check failed")
        print("Please ensure Vitis HLS is installed and sourced:")
        print("  source /opt/Xilinx/Vitis/2024.1/settings64.sh")
        sys.exit(1)
    
    # 创建HLS项目
    if not create_hls_project(verbose=args.verbose):
        print("\nERROR: Failed to create HLS project")
        sys.exit(1)
    
    # 运行C仿真
    if not run_c_simulation(verbose=args.verbose):
        print("\nERROR: C Simulation failed")
        sys.exit(1)
    
    # 检查结果
    if not check_results(verbose=args.verbose):
        print("\nWARNING: Some tests failed")
        print("Please check the logs for details")
        sys.exit(1)
    
    print("\n" + "="*60)
    print("C Simulation Completed Successfully!")
    print("="*60)
    print("Next Steps:")
    print("1. Run HLS Synthesis:")
    print("   python run_synth_bram.py")
    print("2. Check resource utilization:")
    print("   - Target: BRAM <= 105 blocks")
    print("   - Target: Frequency >= 200 MHz")
    print("="*60)
    
    sys.exit(0)

if __name__ == "__main__":
    main()